package eu.fbk.ict.pdi.moki.sopmanager;

public class LuceneConstants {
	
  public static final String sopId = "id";
  public static final String sopFilename = "filename";
  public static final String sopTitle = "title";
  public static final String sopFullText = "text";
  public static final String sopSectionOneText = "textsectionone";
  public static final String sopSectionTwoText = "textsectiontwo";
  public static final String sopSectionThreeText = "textsectionthree";
  public static final String sopSectionFourText = "textsectionfour";
  public static final String sopSectionFiveText = "textsectionfive";
  public static final String sopSectionSixText = "textsectionsix";
  public static final String sopSectionSevenText = "textsectionseven";
  public static final String sopSectionEightText = "textsectioneight";
  public static final String sopType = "category";
  public static final String sopOutLinks = "outlinks";
  public static final String sopInLinks = "inlinks";
  public static final String sopOwningSite = "owningsite";
  public static final String sopApplicabilityAreas = "applicabilityareas";
  public static final String sopApplicabilityAreasRaw = "applicabilityareasraw";
  public static final String title = "title";
  public static final String code = "numrel";
  public static final String authors = "authors";
  public static final String fullText = "fulltext";
  public static final String urls = "allegati";
  public static final String type = "type";
  public static final String abstrac = "abstract";
  public static final String csper = "csper";
  public static final String materiale = "materiale";
  public static final String descmater = "descmater";
  public static final String conten = "conten";
  public static final String dataarch = "dataarch";
  public static final String numlot = "numlot";
  public static final String prod = "prod";
  public static final String uso = "uso";
  public static final String colcont = "colcont";
  public static final String utins = "utins";
  public static final String utmod = "utmod";
  public static final String dtins = "dtins";
  public static final String testataId = "testataId";
  public static final String descmater2 = "descmater2";
  public static final String numstud = "numstud";
  public static final String datastud = "datastud";
  public static final String prog_prod = "prog_prod";
  public static final String societa = "societa";
  public static final String glp_gcp = "glp_gcp";
  public static final String classarch = "classarch";
  public static final String formul = "formul";
  public static final String saggio = "saggio";
  public static final String sommin = "sommin";
  public static final String tipostud = "tipostud";
  public static final String elkeyric = "elkeyric";
  public static final String Datacheck = "Datacheck";
  public static final String DETTAGLIO = "DETTAGLIO";
  public static final String TESTATA = "TESTATA";
  public static final String dtmod = "dtmod";
  
  public static final int MAX_SEARCH = 2000;
}